# Generated by Django 5.0.4 on 2024-05-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
