# Generated by Django 5.0.4 on 2024-05-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.AutoField(default=235, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
