# Generated by Django 5.0.4 on 2024-05-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_remove_transaction_transaction_id_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.AutoField(default=21, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
